server:
  port: 8082
spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:h2:file:~/cards;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
  cloud:
    function:
      definition: updateCardMobileNumber;rollbackCardMobileNumber
    stream:
      bindings:
        updateCardMobileNumber-in-0:
          destination: update-card-mobile-number
          group: ${spring.application.name}
        updateLoanMobileNumber-out-0:
          destination: update-loan-mobile-number
        rollbackAccountMobileNumber-out-0:
          destination: rollback-account-mobile-number
        rollbackCardMobileNumber-in-0:
          destination: rollback-card-mobile-number
          group: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"